### ISSUE TITLE
Nested marathon app IDs not parsed fully

### ISSUE THREAD

**Issue by brentonr** [joshughes/fluent-plugin-mesosphere-filter#3]
When a marathon application ID is nested and set as something like "/group/app", the parsed application name ("app") is "group".

For my use case, I would rather see "app". 

I'm not sure if this is a bug, i.e. is the intended behavior of the regex against MARATHON_APP_ID env intending to match "app" and not "group" from "/group/app"?

Or should this be a request for a new feature where I could configure the marathon regex (like with chronos task IDs).

**Comment by joshughes** [comment]
So I didn't take into account this use case. Currently the regex for parsing marathon app names is the following... 

``` ruby
marathon_regex = '\/(?<app>[a-z0-9]([-a-z0-9_.]*[a-z0-9_.]))'
```

It is not configurable but could easily be made so if you think that would solve your issue.

**Comment by brentonr** [comment]
I agree - I can certainly work with a configurable marathon_regex value.

**Comment by joshughes** [comment]
Cool, I can update the plugin tonight and push a release to close this issue. Thanks for the feedback!

**Comment by panlilu** [comment]
Now you can bump a version and push a release to close this issue. 😄

**Comment by joshughes** [comment]
new version is deployed... closing the issue.
